# -*- coding: utf-8 -*-
"""FFT_selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1afmuRrK04Xw-0Zx5ntD8pEd9T2E0cr0U
"""

import os
import numpy as np
import scipy.io

# 定義資料夾路徑和標準閾值
folder = '/content/test'  # 你的資料夾路徑
standard = 6  # 設定標準閾值，依你的需求調整

def process_file(file_path):
    # 讀取 .mat 文件
    data = scipy.io.loadmat(file_path)
    velocity = data['velocity'].squeeze()
    rel_time = data['time_rel'].squeeze()
    abs_time = data['time_abs'].squeeze()

    # 計算 FFT
    result = np.fft.fft(velocity)
    magnitude = np.abs(result)

    # 取最大振幅
    max_amplitude = np.max(magnitude)

    # 取 log10(最大振幅)
    if max_amplitude == 0:
        log_max_amplitude = -np.inf  # 防止 0 的 log10 出現 -inf
    else:
        log_max_amplitude = np.log10(max_amplitude)

    # 提取第一個和最後一個 time_rel 資料
    first_time = abs_time[0]
    last_time = abs_time[-1]

    # 比較最大振幅取 log 是否大於標準值，並回傳對應結果
    if log_max_amplitude > standard:
        return os.path.basename(file_path), first_time, last_time, 0
    else:
        return os.path.basename(file_path), first_time, last_time, 1

# 遍歷資料夾中的所有文件
results = []
for file in os.listdir(folder):
    if file.endswith('.mat'):
        file_path = os.path.join(folder, file)
        result = process_file(file_path)
        results.append(result)

# 打印結果
for res in results:
    print(res)